### ISSUE TITLE
Add Support for Testing on Windows

### ISSUE THREAD

**Issue by kingmaker-agm** [ob-ivan/diversitest#18]
This package provides support only for the **Linux** and not for **Windows**. It would be great If you could provide a **windows binary `.exe` executable** along with this package.

**Comment by ob-ivan** [comment]
PHP is an interpreted language. PHP programs are not built as binaries, they are executed by an interpreter, which is an executable. PHP interpreter for Windows can be obtained from its official page: https://windows.php.net/download

**Comment by ob-ivan** [comment]
Okay, I'm sorry, I guess I was too hasty. I had thoroughly forgot how this whole project functioned.

I guess you were talking about the shell script?

In any case, Windows binary executable is out of question. I don't have a tiniest clue how (and what for) to build a Windows binary executable. The actions carried out by the runner script (`./diversitest`) are too simple to call for a binary executable. If anything, a PowerShell script could be an option, but then again, I don't have a slightest idea how to code in PowerShell, not to mention that I don't have a Windows machine to test it against.

I can suggest forking and adding a PowerShell script to anyone brave enough to write it. I don't consider myself fit to review and/or maintain it, so no PR please, just fork.

An approach that I could consider adding to this project would be rewriting the runner script in PHP using the (already present) dependency on Symfony/Console.

Still, there is at least one open questions about the Windows operating system that requires an answer before a portable version can be implemented:
* Is there a way to create a temporary directory? See the use of `mktemp` in the runner script.

**Comment by ob-ivan** [comment]
@kingmaker-agm I've released v0.6.1 with the runner script rewritten in PHP using Symfony/Console.

Please see if this works for your case.

**Comment by kingmaker-agm** [comment]
Thanks @ob-ivan for the windows Support. It is working fine on the windows now.

There is a bit Issue which I have opened a separate Issue. #25

**Comment by kingmaker-agm** [comment]
#25
